
[[serialisation]]
[appendix,obligation=informative]
== Reference model XML serialization

The following is a sample serialisation of <<refmodel>> in XML. This is not
intended to be the only
possible serialisation of <<refmodel>>, whether in XML or in another format.
In fact, existing reference tools such as BibTeX <<bibtex>> are
expected to be used as serialisations. The sample serialisation is intended to
provide illustrations
of the model, and to discuss the model succinctly by referencing its elements.
(Of course, the serialisation can be used in practice as a basis for data
exchange of references.)

The serialisation is the canonical grammar of the
https://github.com/relaton/relaton-models[relaton-models] repository,
included verbatim below; refer to <<relaxngcompact_tutorial>> for an
introduction to the format. The repository grammar is the single source
of truth for the serialisation.

[[serialisation_rnc]]
[source,rnc]
.RELAXNG Compact serialisation of the reference model (canonical: relaton-models `relaton/grammars/biblio.rnc`)
--
include::../relaton-models/relaton/grammars/biblio.rnc[]
--
