
[[date]]
=== Date

==== General

* Source: <<ISO690,clause 7.7>>
* Serialisation: `bibitem/date`, `date/@type`, `date/on|from|to`, `date/@text`

The date of publication, manufacture, distribution, execution, transmission, etc., should be cited if necessary. For physical items such as printed books, providing the year is often sufficient to facilitate locatability, but for intangible works (e.g., Internet documents, serials, research datasets and patents), the explicit date and time of the last modification and/or date and time the document was viewed may be necessary.

If appropriate, date may be expressed as shown in the cited information resource or external metadata describing the resource, e.g., the name of a season or a university term.

The format of the date information should be based on representations provided in the <<ISO8601-1,ISO 8601>> series if the information should be machine readable and understandable.

NOTE: The <<ISO8601-1,ISO 8601>> series specifies representations of date and time information for interchangeable purposes, that are sometimes neither familiar nor ideal for human users. For instance, an open time interval intended for human reading is usually represented using an en-dash (e.g. 1990–) or hyphen (e.g. 1990-), whereas its standard-based representation utilizes a solidus and full stops (e.g. 1990/..). In these cases, the human readable form is preferred.

A date is serialised as `date/@type` (the lifecycle phase, from the `BibliographicDateType` vocabulary) with either the point date `date/on`, or the range `date/from` and `date/to`, each in the <<ISO8601-1,ISO 8601>> format. A date that cannot be expressed as a Gregorian date is serialised as text in `date/@text`.

====
MADDOX, Brenda. _DNA's double helix: 60 years since life's deep molecular secrets was discovered_. [online]. The Guardian, 2013-02-22.

[source,xml]
--
<bibitem type="article">
  <title>DNA's double helix: 60 years since life's deep molecular secrets was discovered</title>
  <date type="published"><on>2013-02-22</on></date>
  <relation type="includedIn">
    <bibitem type="periodical">
      <title>The Guardian</title>
    </bibitem>
  </relation>
</bibitem>
--
====

==== Model

For a point date, only `date/on` is populated. For a date range, `date/from`
and `date/to` are populated. If the range is ongoing,
the `date/to` element is left out.

The date for `date/on`, `date/from` and `date/to` is by default given as a
Gregorian date/time, following the conventions
of <<ISO8601-1>>; in an XML serialisation, they would be expected to follow
the XML Schema `xs:datetime` representation (<<xmlschema>>). However bibliographic
dates often contain information that cannot be restricted to an ISO 8601 date
(dates in other calendars, date corrections; other subdivisions of the year;
approximate date or no date.) For that reason, the
model allows dates to be expressed in text instead of as an ISO 8601 date
(`date/on@text`, `date/from@text`, `date/to@text`), or as well as an ISO 8601
date if a Gregorian date is still applicable.
If the textual value of a date is a date range, and ISO 8601
dates are still to be provided for the start and end of the date range, then
the textual value is repeated for `date/from@text` and `date/to@text`.

Date corrections may also involve indications of provenance (<<provenance>>).

The date of copyright is associated expressly with the copyright holder, in
`bibitem/copyright/date/from`. Unlike other bibliographic dates, the copyright
date can only have a year value.

====
ROGET, Peter Mark. _Roget's Thesaurus_. Revised by
Susan M. LLOYD. Burnt Mill, Harlow, Essex: Longman Group Limited, 1982 [1852].

[source,xml]
--
<bibitem type="book">
  <title>Roget's Thesaurus</title>
  <date type="created"><on>1852</on></date>
  <date type="updated"><on>1982</on></date>
  <date type="published"><on>1982</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Roget</surname>
        <forename>Peter</forename>
        <forename>Mark</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="editor">revised</role>
    <person>
      <name>
        <surname>Lloyd</surname>
        <forename>Susan</forename>
        <forename>M.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Longman Group Limited</name>
    </organization>
  </contributor>
  <place>Burnt Mill, Harlow, Essex</place>
</bibitem>
--
====

====
2018-05-09, 21:33:28

<date type="created">
  <on>2018-05-09T21:33:28</on>
</date>
====

====
Jewish calendar 5685 [1925]

<date type="published" text="Jewish calendar 5685"><on>1925</on></date>
====

====
Islamic calendar 1439 [2017–2018]

<date type="created">
  <from text="Islamic calendar 1439">2017</from>
  <to text="Islamic calendar 1439">2018</to>
</date>
====

====
1959 [i.e. 1995]

<date type="created">
  <on>1959</on>
</date>
<date type="created" source="supplied">
  <on text="1959 [i.e. 1995]">1995</on>
</date>
====

====
Michaelmas term (Oxford), 2002

<date type="created">
  <from text="Michaelmas term (Oxford), 2002">2002-10-01</from>
  <to text="Michaelmas term (Oxford), 2002">2002-12-17</to>
</date>
====

====
1650?

<date type="created" text="1650?">
  <on>1650</on>
</date>
====

====
\[no date]

<date type="created" text="[no date]"/>
====

====
1951 copied 1957

<date type="created">
  <on>1951</on>
</date>
<date type="copied">
  <on>1957</on>
</date>
====

====
1951-

<date type="published">
  <from>1951</from>
</date>
====

====
© ISO, 2018

<copyright>
  <from>1951</from>
  <owner><organization><name>ISO</name></organization></owner>
</copyright>
====

[[datetypes]]
===== Date types

Dates are associated with specific phases of the production of a bibliographic
item, and those phases  are named through `date@type`.
The default type used in bibliography
is the date of publication (`date[@type = "published"]`), but the "created",
"updated", "unchanged", and "copied" dates in particular
are often given where they differ from the date of publication.
The date of transmission is used instead of the date of publication
for a broadcast.

The repertoire of date types is expanded to deal with the particular requirements
of standards:

Normal bibliographic dates:

created:: Date a resource was created.
published:: Date a resource was published.
accessed:: Date a resource was last accessed by the bibliographer; routinely used
for online publications. (Unlike in <<ISO690>>, no distinction is made between
"viewed" and "accessed" based on whether the resource is human-readable or
machine-readable.)
updated:: Date a resource was updated and republished. Used for new editions.
unchanged:: Date a resource was reprinted, i.e. republished without any changes.
circulated:: Date a draft version of a resource was circulated. (Drafts by definition
are not published.)
transmitted:: Date a resource was broadcast.
copied:: Date a resource was physically copied, or recreated without any substantial
change in content (allowing for change in medium).
adapted:: Date a resource was adapted for a new purpose or audience, with some change
in content (includes translation).

Standards bibliographic dates:

implemented:: Date a standard takes effect.
obsoleted:: Date a standard becomes no longer in effect.
confirmed:: Date a standard is renewed to take effect.
issued:: Date a standard is authorised for publication.

The date of publication is taken to be the date when the current version of the resource
was published, unless a separate "unchanged", "updated" or "copied" date is given;
in that case, the date of publication is assumed to be the date of initial publication.

The date of creation is taken to apply to the work instantiated by the resource,
rather than to a specific format or edition. The latter are represented by the date
of adaptation and of update, respectively.

==== Representation

[[date_year]]
===== Year

The year should usually be given as it appears in the cited information resource, however, years written as words in the cited information resource should be given as Arabic numerals in the reference.

If the cited information resource bears a date from a calendar system other than the Common Era (CE), the date should be given together with its <<ISO8601-1>> equivalent in the CE calendar system supplied as associated information.

====
Jewish calendar 5685 [1925].
====

====
唐貞觀元年 [Zhengguan era of the Tang dynasty, year 1] [627].
====

====
中華民國元年 [Calendar of the Republic of China, year 1] [1911].
====

====
平成３１年 [Heisei era, year 31] [2019].
====

====
L'AN VI [1798].
====

[[season_month_day_time]]
===== Season, month, day, time

If a machine readable date is required, it should be provided in a format compliant with the <<ISO8601-1,ISO 8601>> series, including, if necessary, time. In that case, the time zone may also be provided.

====
1984-02-10T13:43:11Z.
====

====
1984-22. (Summer 1984)
====

====
MANN, T. _Letter to Hermann Hesse_, 1951-10-14
====

====
MADDOX, Brenda. _DNA's double helix: 60 years since life's deep molecular secrets was discovered_. [online]. The Guardian, 2013-02-22.
====

The precise date may be provided with the season or month spelled out, either in full or abbreviated, and with day, month, year and time given in the order and language used in the cited resource (see <<reference_elements_general>>). If so, an <<ISO8601-1,ISO 8601>> equivalent of the date may also be provided as associated information after the date from the cited resource.

====
June 22, 2019.
====

====
10 Feb. 1984 [1984-01-10].
====

====
10{period} tammikuuta 1984 [1984-01-10].
====

====
Chinese lunar calendar date: Winter (month 1), day 10, 2019 [2019-02-14].
====

====== Uncertain, unknown, approximate or missing date

If the year of publication is not given but can be ascertained, it should be supplied. If the date is uncertain, an approximate date, followed by a question mark should be provided.

The character X may be used in place of one or more rightmost digits to indicate that the value of that digit is unspecified. Approximate date may be specified with tilde ("`~`"), uncertain and approximate date with percent character ("`%`").

If no date can be given, the Latin phrase "`s. a.`", English phrase "`no date`" (or "`n. d.`"), or an equivalent in the language of the publication may be supplied.

====
[1750].
====

====
[1873?]. (Uncertain year, possibly 1873)
====

====
[177X]. (The resource is known to have been published between 1770 and 1779.)
====

====
[1984~]. (Approximate year)
====

====
[1914%]. (Uncertain and approximate year, possibly 1914)
====

====
[no date].
====


====== Date ranges

Date ranges should be created using the Unicode "`hyphen-minus`" as the separator character. Open ranges are acceptable.

====
1940–.
====

====
1978–, Jahrg. 5–.
====

====
1936–1941, año 1–6.
====

====
1970–1973, vols 1–3. [Discontinued].
====

If the date range has to be machine readable, it may be expressed as specified in <<ISO8601-1,ISO 8601>>. The standard uses solidus ("`/`") as the separator character in ranges.

====
1970/1973, vols 1–3. [Discontinued].
====


[[date-publication]]
===== Date of publication

The year (and, if necessary, full date or date and time) on which the cited information resource was published should be given.

====
1997.
====

====
June 22, 2019.
====

In a reference to the whole or a limited run of any item issued in parts over a period of years, the years of publication of the first part issued (which is not necessarily numerically the first part) and the part last issued should be given.

====
1842–1898.
====


If the run is in progress, the year of the first item should be provided, followed by a hyphen-minus. The numeration and pagination (see <<numeration>>), if any, should also be given.

====
1842–.
====



[[date-citation]]
===== Date of citation

The full date (and, if necessary, time) on which the cited information resource was viewed should be given if:

. The cited information resource is dynamic, and it is necessary to indicate the exact version used with the date.
. There is no other date information to be found either in the cited information resource or in the related documentation such as external metadata.

The date of citation should be preceded by an appropriate term such as "viewed" and "accessed" (for human and machine-readable information resources, respectively) or equivalent terms in the language of the publication.

The date the cited resource was viewed should follow the link used. Even a single citation may contain several links to different copies or versions of the cited information resource, and it may be important to indicate when the functionality of these links was checked.

====
[viewed 2016-09-03].

[source,xml]
--
<date type="accessed"><on>2016-09-03</on></date>
--
====


===== Surrogate dates

In a reference to a reprint, facsimile, digital surrogate or other copy of the original information resource, the date of publication of that edition or, for a copy, the date of the original, should be given, along with the date of reprinting or copying.

====
1796 [copied 1810].
====

====
1870 [digitized 2010].
====


===== Incorrect dates

If the date given on the cited information resource is known to be incorrect, the correct year should also be supplied in brackets after the date in the cited resource.

====
1959 [i.e. 1995].
====

If the date on the cited information resource is known to be different from the actual publication date, both dates may be given; the actual date in brackets after the date in the cited resource.

