
[[numeration]]
=== Numeration and pagination

==== General

* Source: <<ISO690,clause 4.7>>; <<ISO690,clause 7.9>>
* Serialisation: `bibitem/extent`

The components of the cited information resource should be referred in the terms used in the resource, their order following the principle that the larger precedes the smaller.

Components of an item are modelled under the `bibitem/extent` element as
one or more "localities"; these consist of a locality type
(`bibitem/extent@type`), a locality value (`bibitem/extent/referenceFrom`),
and optionally a locality range endpoint (`bibitem/extent/referenceTo`).
The `extent` gives the part of the host item being cited, if this is a
contained item (<<host-item>>), such as a journal article or book chapter
(e.g. "pp. 25-45").

Some electronic formats such as PDF may retain the pagination of the original (printed) resource, but some other formats may not have the pagination. If so, logical components of the cited information resource should be used.

====
chapter 2, paragraphs 5–9.
====

A hierarchical locality is expressed by repeating the extent element
with the different applicable locality types; these should be given in
hierarchical order. However localities in an extent
may be complimentary instead (e.g. "xiii+179 pp" for prefatory and main
pagination; "114pp + 3 plates" for plates outside the main page numeration).

Discontinuous ranges are modelled by repeating the extent element for the same locality type.

Extent includes the volume and issues of a journal, if the
item is an article in the journal.

If the item is not a component of another item, then the extent gives the
locality value for the entire work (e.g. page count: "[7 pp.]"). This is expressed
by giving an empty `bibitem/extent/referenceFrom`, and populating
only `bibitem/extent/referenceTo` ("[7 pp.]" = pp. 1-7).

If a locality is labelled conventionally with a range, but is in fact a single
item (as often occurs with volumes and issues; e.g. issue 18–19 is in fact a
single issue), the label should be associated with
`bibitem/extent/referenceFrom` rather than being treated as a true range.
However the rendering of the item will typically not be any different.

A part of a contained item may be cited, and this has posed difficulty for
some citation schemes (e.g. citing a page within a journal article, which itself
covers a page range: "Dedes, D. 1993. Ποίηματα του Μαυλανά Ρουμή [Poems by
Mevlana Rumi]. _Ta Istorika_ 10.18-19: 3-22. pp. 7-19".) However, the model
copes with this by separating the extent of a citation <<citationmodel>>
from the extent of a bibliograhic item, and the extent of a contained item
from the extent of a host item. In this instance, "pp. 7-19" would be treated
normally as part of the citation, not part of the bibliographic item.

====
Dedes, D. 1993. Ποίηματα του Μαυλανά Ρουμή [Poems by Mevlana Rumi]. _Ta Istorika_ 10.18-19: 3-22.

[source,xml]
--
<bibitem type="article">
  <title lang="en">Poems by Mevlana Rumi</title>
  <title type="original" lang="ell">Ποίηματα του Μαυλανά Ρουμή</title>
  <date type="published"><on>1993</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Dedes</surname>
        <forename>Dimitrios</forename>
      </name>
    </person>
  </contributor>
  <series>
    <title>Ta Istorika</title>
  </series>
  <extent type="volume">
    <referenceFrom>10</referenceFrom>
  </extent>
  <extent type="issue">
    <referenceFrom>18–19</referenceFrom>
  </extent>
  <extent type="page">
    <referenceFrom>3</referenceFrom>
    <referenceTo>22</referenceTo>
  </extent>
</bibitem>
--
====

====
Brown, P. L. (1999, September 5). Tiffany glass and other tales from the crypt.
_The New York Times_, pp. 1, 5.

[source,xml]
--
<bibitem type="article">
  <title>Tiffany glass and other tales from the crypt</title>
  <date type="published"><on>1999-09-05</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Brown</surname>
        <initials>P. L.</initials>
      </name>
    </person>
  </contributor>
  <series>
    <title>The New York Times</title>
  </series>
  <extent type="page">
    <referenceFrom>1</referenceFrom>
  </extent>
  <extent type="page">
    <referenceFrom>5</referenceFrom>
  </extent>
</bibitem>
--
====


[[numeration_part_cited]]
==== Part cited

The reference should identify the part of the information resource that is cited. For a component part, the number and designation of the smallest separately identified component should be given.

====
vol. 6, no. 3, pp. 25–45.
====

====
vol. 2, plate XXV.
====

====
fiche 4, frame B5.
====


If the entire information resource is being cited, its extent may optionally be stated in brackets. The extent should be given, if the cited resource is large.

====
https://doi.org/10.14296/resaw.0004[https://doi.org/10.14296/resaw.0004] [7 pp].
====

====
https://doi.org/10.3886/ICPSR31521.v1[https://doi.org/10.3886/ICPSR31521.v1] [2 GB]
====

====
Ramsey, J. K., & McGrew, W. C. (2005). Object play in great apes: Studies in nature and captivity.
In A. D. Pellegrini & P. K. Smith (Eds.), _The nature of play: Great apes and humans_
(pp. 89-112). [308pp]. New York, NY: Guilford Press.

[source,xml]
--
<bibitem type="incollection">
  <title>Object play in great apes: Studies in nature and captivity</title>
  <date type="published"><on>2005</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Ramsey</surname>
        <initials>J. K.</initials>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>McGrew</surname>
        <initials>W. C.</initials>
      </name>
    </person>
  </contributor>
  <relation type="includedIn">
    <bibitem>
      <title>The nature of play: Great apes and humans</title>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Pellegrini</surname>
            <initials>A. D.</initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Smith</surname>
            <initials>P. K.</initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="publisher"/>
        <organization>
          <name>Guilford Press</name>
        </organization>
      </contributor>
      <place>New York, NY</place>
      <extent type="page">
        <referenceTo>308</referenceTo>
      </extent>
    </bibitem>
  </relation>
  <extent type="page">
    <referenceFrom>89</referenceFrom>
    <referenceTo>112</referenceTo>
  </extent>
</bibitem>
--
====

[[numeration_omission]]
==== Omission of terms

Previous editions of this document allowed omission of the term "volume" and terms for smaller component parts of serial publications. Typographic means were then used to distinguish the volume number and the part number, with the volume number in bold type and the part number, if required, in parentheses.

====
*6*(3), 25–45.
====

In this edition, such practice is no longer allowed. Font styles should not be used to replace or indicate information, because individuals with limited sight or reading disabilities may not be able to distinguish between bold and regular font. Also, generally, a proprietary software, such as Microsoft Word is needed to view bold or italics. In preparation for machine-readable citations, it is important for citation data to be provided in a format that is easily recognizable by a machine, such as a plain text file.

====
_Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling_. Edited by Susan Gross Solomon. New York: St. Martin's Press, 1983. xiii, 179 pp. $27.50.

[source,xml]
--
<bibitem type="book">
  <title>Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling</title>
  <date type="published"><on>1983</on></date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <surname>Solonom</surname>
        <forename>Susan</forename>
        <forename>Gross</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>St Martin's Press</name>
    </organization>
  </contributor>
  <note>$27.50</note>
  <place>New York</place>
  <extent type="page">
    <referenceTo>xiii</referenceTo>
  </extent>
  <extent type="page">
    <referenceTo>179</referenceTo>
  </extent>
</bibitem>
--
====

====
John H. Stewart, Edwin H. McKee, and Harold K. Stager.
_Geology and mineral deposits of Lander County, Nevada_.
Nevada Bureau of Mines and Geology Bulletin 88. 1977.
Reno: University of Nevada. [114 pp, 3 plates]

[source,xml]
--
<bibitem type="book">
  <title>Geology and mineral deposits of Lander County, Nevada</title>
  <date type="published"><on>1977</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Stewart</surname>
        <forename>John</forename>
        <forename>H.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>McKee</surname>
        <forename>Edwin</forename>
        <forename>H.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Stager</surname>
        <forename>Harold</forename>
        <forename>K.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>University of Nevada</name>
    </organization>
  </contributor>
  <place>Reno</place>
  <series>
    <title>Nevada Bureau of Mines and Geology Bulletin</title>
    <number>88</number>
  </series>
  <extent type="page">
    <referenceTo>114</referenceTo>
  </extent>
  <extent type="plate">
    <referenceTo>3</referenceTo>
  </extent>
</bibitem>
--
====
