
[[additional-info]]
== Additional general information

[[provenance]]
=== Provenance

Information in a reference typically comes from the publisher of a resource, and
is included in the resource itself, as described in <<ISO690,clause 4.1.2>>.
<<ISO690,clause 4.1.2>> permits information to be supplied by other parties, and
differentiated by including it in brackets. This can include both missing
information (e.g. "[Untitled]"), and corrections (e.g. "1959 [i.e. 1995]").

The party supplying emendations to reference information is identified in
<<ISO690,clause 4.1.2>>
as the citer of the reference. However, the citer should be differentiated from
the bibliographer,  in the case of bibliographies as consumable resources (e.g.
as bibliographic databases):

* The publisher provides the primary source information about the resource,
typically in the resource itself, but also as a feed of information to a
bibliographer.
* The bibliographer compiles a bibliography as a list of references, and uses
their judgement to supply information and to impose uniform representation and
rendering of the list.
* The citer uses a bibliography within a resource, to identify cited resources,
and may further adjust the bibliography they provide within the resource (e.g.
for disambiguation, or to disaggregate references included in other references.

The bibliographer and the publisher in the contemporary bibliography universe
are more active parties than in the traditional model, which relies exclusively
on citer discretion. Bibliographers
and publishers are invested in asserting that they are sources of truth about
bibliographic
resources; and the bibliographies covered by any model of electronic exchange
include references
provided by bibliographers and publishers, in bibliographic databases—as well as
the references consumed and adjusted by citers from bibliographic databases.

So the original reference as obtained from a bibliographic database may need to
be differentiated
from any adjustments made to the reference by a citer; and the citer adjustments
in some contexts may need to be overridden.

If the serialisation of bibliographic items is to reflect such adjustments to content,
it will need to indicate the provenance of bibliographic information, and allow
multiple versions of the same information, with differing provenance. At the simplest level
there will simply be
two or more different versions of the reference serialisation, some representing
the publisher or
bibliographer's source of truth, and some representing the citer's adjustments
(in brackets).
Adjustments made by the bibliographer would also be represented in brackets;
this is long-standing routine practice in library catalogues.

A more granular approach would be to permit multiple instances of any element in
the reference
model, differentiated by provenance: this could be done with a child element
(e.g. an XML attribute),
or with a nested container. If no provenance is indicated, the information is
assumed to be
unchanged from the source of truth. A renderer can then choose which alternative
to render depending on local requirements:

.Differential Provenance
====
[source,xml]
--
<bibitem>
  <date><on>1959</on></date>
</bibitem>

<bibitem source="citer">
  <date><on>1959 [i.e. 1995]</on></date>
</bibitem>

<bibitem>
  <date><on>1959</on></date>
  <date source="citer"><on>1959 [i.e. 1995]</on></date>
</bibitem>
--
====

NOTE: Breaking out completions and emendations into separate elements in the model
(e.g. `<date><on><orig>1959</orig><corr>1995</corr></on></date>`)
is not desirable,
given how open-ended emendations can be (e.g. appearing anywhere in a string):
they would complicate any serialisation of the model, to little real benefit.



=== Classification

* Source: <<ISO690,clause 4.11>>
* Serialisation: `bibitem/classification`

====
Giesler, Patricia. _Canada Remembers the Korean War_. Dewey 971.06 GIE 2003.
ISBN 0662674979. Charlottetown, P.E.I. : Veterans Affairs Canada. 2003.

[source,xml]
--
<bibitem type="book">
  <title>Canada Remembers the Korean War</title>
  <docidentifier type="ISBN">0662674979</docidentifier>
  <date type="published"><on>2003</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Giesler</surname>
        <forename>Patricia</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Veterans Affairs Canada</name>
    </organization>
  </contributor>
  <place>Charlottetown, P.E.I.</place>
  <classification type="Dewey">971.06 GIE 2003</classification>
</bibitem>
--

====

=== Keywords

* Source: N/A
* Serialisation: `bibitem/keyword`

====
[source,xml]
--
<keyword>Homo sapiens</keyword>

<keyword>
  <vocab>Homo sapiens</vocab>
  <vocabid type="wikidata" uri="https://www.wikidata.org/wiki/Q15978631">
    <code>Q15978631</code>
    <term>Homo sapiens</term>
  </vocabid>
  <vocabid type="National Biodiversity Network">
    <code>NHMSYS0000376773</code>
  </vocabid>
</keyword>

<keyword>
  <taxon>Hominidae</taxon>
  <taxon>Homininae</taxon>
  <taxon>Hominini</taxon>
  <taxon>Hominina</taxon>
  <taxon>Homo</taxon>
  <taxon>Homo sapiens</taxon>
  <vocabid type="wikispecies"><term>Homo_sapiens</term></vocabid>
</keyword>
--
====

=== Price and availability

* Source: <<ISO690,clause 4.11>>
* Serialisation: `bibitem/price`, `bibitem/note`


Price is marked up as a distinct element, which contains the currency code, represented in ISO 4217.
The price should be treated as nominal, rather than capturing all possible pricings at a given time.

Availability information for a bibliographic item is treated
as a note. This also applies to the availability of an online resource,
and any access limitations, but not to licensing, which is encoded separately.

====
_Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling_.
Edited by Susan Gross Solomon. New York: St. Martin's Press, 1983. xiii, 179 pp.
$27.50. Available on request to the author.

[source,xml]
--
<bibitem type="book">
  <title>Pluralism in the Soviet Union: Essays in Honour of H. Gordon Skilling</title>
  <date type="published"><on>1983</on></date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <surname>Solonom</surname>
        <forename>Susan</forename>
        <forename>Gross</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>St Martin's Press</name>
    </organization>
  </contributor>
  <note>Available on request to the author</note>
  <place>New York</place>
  <price currency="USD">27.50</price>
  <extent type="page">
    <referenceFrom>xiii</referenceFrom>
  </extent>
  <extent type="page">
    <referenceFrom>179</referenceFrom>
  </extent>
</bibitem>
--
====

=== License

* Source: <<ISO690,clause 4.11>>
* Serialisation: `bibitem/license`, `bibitem/copyright`.

Where available, URIs should be used to identify licenses unambiguously.
If a URI is not available, a commonly accepted abbreviation or short name of
the license should be used.

Copyright is privileged with a separate element, incorporating copyright date
and owner.

====
<license>BSD-2</license>
<license>https://creativecommons.org/licenses/by/2.0/</license>
====

=== Provenance and Authenticity

* Source: <<ISO690,clause 4.11>>
* Serialisation: `bibitem/note`

Notes on bibliographical provenance, and checksums for digital resources,
are both given as bibliographic notes.



